# _config.yml
title: Dinh Thien Bao (Kaiversus)
description: "Portfolio of Dinh Thien Bao (Kaiversus) - Security Researcher and CTF Player."
url: "https://kaiversus.github.io"
baseurl: ""

# Định nghĩa 3 kho dữ liệu riêng biệt
collections:
  writeups:
    output: true
    permalink: /writeups/:path/
  courses:
    output: true
    permalink: /courses/:path/
  projects:
    output: true
    permalink: /projects/:path/
# --- Dán đoạn này vào cuối file _config.yml ---

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "writeups"
    values:
      layout: "writeup"

defaults:
  - scope:
      path: ""
      type: "scorses"
    values:
      layout: "scorse"
